### ISSUE TITLE
missing connect() in onResume method

### ISSUE THREAD

**Issue by spietre** [Jorgesys/Android-Google-Drive#1]
This code was not working for me. I found out that if I add connect() into onResume() method than it works. So this is how it works for me:

`protected void onResume() { 
        super.onResume();
        if (mGoogleApiClient != null) {
            mGoogleApiClient.connect();
        }
    }`

**Comment by Jorgesys** [comment]
Thank you, you can call in `onResume()` the method for initialization `connectAPIClient()` :    
```
 @Override
    protected void onResume() {
       connectAPIClient();
        super.onResume();
    }
```
